### PR TITLE
Use `&mut` and mutex lock to safely make `Image` implement `Send`

### PR DESCRIPTION
**Pull request by ids1024**
Alternative to https://github.com/cmeissl/pixman-rs/pull/18, as discussed.

Probably should be tested in Smithay to make sure the API changes work well.

### CODE REVIEW

**Comment by Drakulix** [comment]
I hate how brittle this seems. (It is way too easy to forget calling the `Mutex` when new methods are ever introduced.) But it looks like it should work just fine.

**Comment by ids1024** [comment]
Yeah. But it's not too bad since only `Drop` and `set_alpha_map`/`clear_alpha_map` need to use the `Mutex`.

I wish there was some way to test something like this though.

**Comment by ids1024** [comment]
Added a `Sync` implementation as well as `Send`. I believe that is correct. And I renamed the feature to `sync` (I don't think there's a standard name for a feature like this, but that seems reasonable.)

**Review by cmeissl — APPROVED** [review]
Thanks!

**Pull request merged**
